# Generated by Django 4.0.6 on 2022-08-12 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('route', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('submission_type', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('travel_time', models.CharField(max_length=200)),
                ('delay', models.CharField(max_length=200)),
                ('text', models.CharField(default='N/A', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
