# Generated by Django 4.0.5 on 2022-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='route',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
